### ISSUE TITLE
How to use in the Webform

### ISSUE THREAD

**Issue by phamtuan2605** [bbraithwaite/HybridOrm#1]
I am newbie. Please guide used in an application Webform. Thanks!

**Comment by bbraithwaite** [comment]
That's very difficult to answer here and not to mention a very open ended question with many possible answers, and also beyond the scope of an issue with the lib itself!

You may want to start with something like this first? 

https://www.asp.net/web-forms/overview/older-versions-getting-started/getting-started-with-ef/the-entity-framework-and-aspnet-getting-started-part-1

http://www.codeproject.com/Articles/439688/Creating-ASP-NET-application-with-n-tier-architect
